### PR TITLE
WIP - Manual rebase

### PR DESCRIPTION
**Pull request by carlfm01**
Hello @reuben, I had to rebase manually, I could not solve the git large out of quota, still need to complete 1 epoch to make sure nothing is broken with the rebase and compile for TF2 and see if we miss a kernel.

### CODE REVIEW

**Comment by carlfm01** [comment]
Conflicts :'(

**Comment by reuben** [comment]
Git LFS has run out of quota on the parent repo and there's nothing we can do about it. Just need to take out large files and put them in e.g. a GitHub release.

**Comment by reuben** [comment]
I'll take a look at what happened with the Git weirdness here...

**Comment by carlfm01** [comment]
@reuben Don't worry, I can take a look, I just need you to remove the large files, and then I can checkout.

**Comment by reuben** [comment]
@carlfm01 master on this fork should now be even with mozilla/DeepSpeech and have no Git LFS files.

**Comment by reuben** [comment]
Sorry for taking so long I didn't see your reply until now.

**Comment by carlfm01** [comment]
@reuben Closing here, I'll open a new one

**Comment by carlfm01** [comment]
Hello @reuben it still shows the same error message while checking out reuben:quartznet :( can you take a look?

**Pull request closed without merging**
